### ISSUE TITLE
Will web data.php and data.txt  What is the content??  I use blank content to upload 000webhost  But I can't display the victim information during the test

### ISSUE THREAD

**Issue by kk159963** [AnderMoralDiaz/slam-ransomware-builder#1]
Will web data.php and data.txt

What is the content??

I use blank content to upload 000webhost

But I can't display the victim information during the test

**Comment by AnderMoralDiaz** [comment]
the files are located in C:\slam_ransomware_builder\server
remember to give permissions to data.php, the server interface has bugs right now, in a few days I will release version 1.8 which fixes that and includes the option to steal files from the victim, so try it but before sending it to a victim wait for 1.8 to be released.

**Comment by kk159963** [comment]
Thanks I found it!!

I think this work is great

I am looking forward to the new version I am also learning and researching
